package globals

import _ "embed"

//go:embed Ackbar_Delta_SoH_N64_NTSC_10_Audio_Stub.xml
var ackbar_delta_soh_n64_ntsc_10_audio_file []byte

//go:embed Keiichi_Charlie_2S2H_N64_US_Audio_Stub.xml
var keiichi_charlie_2s2h_n64_us_audio_file []byte

var SampleXmls = map[string][]byte{
	"ackbar_delta_soh_n64_ntsc_10": ackbar_delta_soh_n64_ntsc_10_audio_file,
	"keiichi_charlie_2s2h_n64_us":  keiichi_charlie_2s2h_n64_us_audio_file,
}

var SupportedVersions = []string{
	"Keiichi_Charlie_2S2H",
	"Battler_Bravo_2S2H",
	"Uncapped_Banks_2S2H",
	"Ackbar_Delta_SoH",
}

// This was generated by utils/xmls/generateGlobalsFiles.js
