package globals

import "github.com/frogssoldseparately/shippacker/pkg/iohelper"

func SetupByVersion() error {
    switch Version {
    case "Keiichi_Charlie":
		MaxBankCount = 255
		MaxSongCount = 1923
		UseCRC64Encoding = false
		UseNumericCategories = false
	case "Better_Categories":
		MaxBankCount = 255
		MaxSongCount = 1923
		UseCRC64Encoding = false
		UseNumericCategories = true
		Version = "Keiichi_Charlie"
		if err := iohelper.WarnUnstable(); err != nil {
			return err
		}
	case "Uncapped_Banks":
		MaxBankCount = 65535
		MaxSongCount = 1923
		UseCRC64Encoding = true
		UseNumericCategories = true
		Version = "Keiichi_Charlie"
		if err := iohelper.WarnUnstable(); err != nil {
			return err
		}
    default: // Some future version of 2ship with reworked audio
        MaxBankCount = 65535 // exclusive
        MaxSongCount = 65535 // inclusive
        UseCRC64Encoding = true
        UseNumericCategories = true
    }
    return nil
}

// This was generated by utils/xmls/generateGlobalsFiles.js from resources/setup.json
